name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest src/test_model.py -v

    - name: Upload model artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model_*.pth